In [1]:
import numpy

In [2]:
WIDTH = HEIGHT = 100

In [50]:
state = [numpy.zeros((WIDTH, HEIGHT, 2)), 0, 0, numpy.random.uniform([0,0],[10,10], 2)]

In [5]:
int(WIDTH*0.25)

25

In [7]:
site_1 = numpy.array([int(WIDTH*0.25), int(HEIGHT*0.25)])
site_2 = numpy.array([int(WIDTH*0.75), int(HEIGHT*0.75)])

In [12]:
numpy.random.normal([5,5], 5)

array([ 4.47522474, 10.28419254])

In [16]:
numpy.clip([5,0], 4, 6)

array([5, 4])

In [17]:
def random_point_in_grid(center, std):
    p = numpy.random.normal(center, std)
    p = numpy.array([numpy.clip(trial_x[0], [0, WIDTH]), numpy.clip(trial_x[1], [0, HEIGHT])])
    return p

In [19]:
numpy.linalg.norm(site_1 - site_2)

70.71067811865476

In [48]:
numpy.random.uniform([0,0],[10,10], 2)

array([6.93000447, 9.35658391])

In [53]:
state[3] + 0*numpy.array([0,1])*2

array([1.44940182, 4.89034428])